# Generated by Django 5.1.15 on 2026-02-13 16:24

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('ingesting', 'Ingesting'), ('processing', 'Processing'), ('assembling', 'Assembling'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('source_file', models.CharField(max_length=1024)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_type', models.CharField(blank=True, default='', max_length=10)),
                ('detected_language', models.CharField(blank=True, default='en', max_length=20)),
                ('total_pages', models.IntegerField(default=0)),
                ('pages_completed', models.IntegerField(default=0)),
                ('pages_failed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('nfs_job_path', models.CharField(blank=True, default='', max_length=1024)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_worker', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=2048)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_status', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline'), ('draining', 'Draining')], default='offline', max_length=20)),
                ('queues', models.JSONField(default=list)),
                ('capabilities', models.JSONField(default=list)),
                ('concurrency', models.IntegerField(default=4)),
                ('gpu_available', models.BooleanField(default=False)),
                ('gpu_model', models.CharField(blank=True, default='', max_length=255)),
                ('gpu_vram_mb', models.IntegerField(default=0)),
                ('cpu_cores', models.IntegerField(default=0)),
                ('ram_mb', models.IntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_failed', models.IntegerField(default=0)),
                ('current_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('pipeline_version', models.CharField(blank=True, default='', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('event_hash', models.CharField(blank=True, default='', max_length=64)),
                ('chain_finalized', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='jobs.job')),
            ],
            options={
                'ordering': ['document_id', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=64)),
                ('page_num', models.IntegerField()),
                ('ocr_method', models.CharField(blank=True, default='', max_length=50)),
                ('ocr_language', models.CharField(blank=True, default='', max_length=20)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('text_length', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('worker_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('temp_pdf_path', models.CharField(blank=True, default='', max_length=1024)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_results', to='jobs.job')),
            ],
            options={
                'ordering': ['job', 'page_num'],
                'unique_together': {('job', 'page_num')},
            },
        ),
    ]
