# Generated by Django 5.1.15 on 2026-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='storage_backend_used',
            field=models.CharField(blank=True, default='', help_text='Storage backend locked at ingest time (nfs or s3)', max_length=10),
        ),
    ]
