# Generated by Django 5.1.15 on 2026-02-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_storage_backend_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='gpu_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
