# Generated by Django 5.1.15 on 2026-03-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_worker_gpu_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiiEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='e.g., SSN, DOB, EMAIL, PHONE, NAME', max_length=50)),
                ('entity_value', models.TextField(help_text='The extracted PII/PHI text')),
                ('bounding_box', models.JSONField(default=list, help_text='Spatial coordinates [x1, y1, x2, y2]')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score from 0.0 to 1.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_entities', to='jobs.job')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_entities', to='jobs.pageresult')),
            ],
            options={
                'ordering': ['page', 'entity_type'],
                'indexes': [models.Index(fields=['job', 'entity_type'], name='jobs_piient_job_id_84987f_idx'), models.Index(fields=['page', 'entity_type'], name='jobs_piient_page_id_cb7255_idx')],
            },
        ),
    ]
