# Generated by Django 5.1.15 on 2026-05-16 13:55

import jobs.encrypted_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_federation_failover'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='jobs_docume_job_id_2cb984_idx',
            old_name='jobs_docume_job_id_a3f2c5_idx',
        ),
        migrations.RenameIndex(
            model_name='extractedentity',
            new_name='jobs_extrac_entity__e887ac_idx',
            old_name='jobs_extrac_entity__bab32e_idx',
        ),
        migrations.RenameIndex(
            model_name='extractedentity',
            new_name='jobs_extrac_job_id_718271_idx',
            old_name='jobs_extrac_job_id_e8f6a4_idx',
        ),
        migrations.RenameIndex(
            model_name='extractedformvalue',
            new_name='jobs_extrac_field_k_e34e79_idx',
            old_name='jobs_extrac_field_k_c4d1a7_idx',
        ),
        migrations.RenameIndex(
            model_name='extractedformvalue',
            new_name='jobs_extrac_job_id_e64ddb_idx',
            old_name='jobs_extrac_job_id_1a73b2_idx',
        ),
        migrations.AlterField(
            model_name='apikeyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='piientity',
            name='entity_value',
            field=jobs.encrypted_field.EncryptedTextField(help_text='The extracted PII/PHI text'),
        ),
    ]
