import { describe, expect, it } from "vitest";
import {
  canonicalize,
  recomputeEventHash,
  verifyChain,
  type CustodyEvent,
} from "@/lib/audit-verify";

// --------------------------------------------------------------------------
// Reference fixtures.
//
// The hashes below were generated by ``python custody.py``-equivalent code
// (see the worktree implementation note in audit-verify.ts). They are pinned
// here so the JS canonical encoder is regression-tested against the live
// producer.
// --------------------------------------------------------------------------

const event1: CustodyEvent = {
  document_id: "doc-1",
  event_type: "file_ingested",
  timestamp: "2026-04-26T10:00:00.000+00:00",
  data: { source_path: "/in/foo.pdf", size: 1024 },
  prev_hash: null,
  hash: "b7a5c5b6ad0c3fe333c619f4de1d3609bcad7d06a960dc59ed36e40c39ad10b0",
};

const event2: CustodyEvent = {
  document_id: "doc-1",
  event_type: "page_extracted",
  timestamp: "2026-04-26T10:00:01.000+00:00",
  data: { page: 1 },
  prev_hash: event1.hash,
  hash: "e16331b7a8e40241b18aae80be56cf6cb8fe970b4e5b5e4beae4d425ba435667",
};

const event3: CustodyEvent = {
  document_id: "doc-1",
  event_type: "ocr_primary",
  timestamp: "2026-04-26T10:00:02.000+00:00",
  data: { page: 1, engine: "paddleocr", confidence: 0.97 },
  prev_hash: event2.hash,
  hash: "11b5d32beec9958459ca9e784c7f2e5fb1acd57e2b17d1781106144874a75207",
};

describe("canonicalize", => {
  it("emits keys in lexicographic order with Python-compatible whitespace", => {
    const canonical = canonicalize({
      document_id: "doc-1",
      event_type: "file_ingested",
      timestamp: "2026-04-26T10:00:00.000+00:00",
      data: { source_path: "/in/foo.pdf", size: 1024 },
      prev_hash: null,
    });
    expect(canonical).toBe(
      '{"data": {"size": 1024, "source_path": "/in/foo.pdf"}, "document_id": "doc-1", "event_type": "file_ingested", "prev_hash": null, "timestamp": "2026-04-26T10:00:00.000+00:00"}'
    );
  });

  it("emits null / true / false / numbers as bare tokens", => {
    expect(canonicalize({ a: null, b: true, c: false, d: 42 })).toBe(
      '{"a": null, "b": true, "c": false, "d": 42}'
    );
  });

  it("emits non-ASCII strings as \\uXXXX escapes", => {
    expect(canonicalize({ x: "résumé" })).toBe(
      '{"x": "r\\u00e9sum\\u00e9"}'
    );
  });
});

describe("recomputeEventHash", => {
  it("matches the producer hash for a known-good event", async => {
    const computed = await recomputeEventHash(event1);
    expect(computed).toBe(event1.hash);
  });

  it("matches across the full chain", async => {
    expect(await recomputeEventHash(event2)).toBe(event2.hash);
    expect(await recomputeEventHash(event3)).toBe(event3.hash);
  });
});

describe("verifyChain", => {
  it("returns 'empty' for an empty chain", async => {
    const result = await verifyChain([]);
    expect(result.status).toBe("empty");
    expect(result.totalEvents).toBe(0);
  });

  it("returns 'intact' for a known-good 3-event chain", async => {
    const result = await verifyChain([event1, event2, event3]);
    expect(result.status).toBe("intact");
    expect(result.totalEvents).toBe(3);
    expect(result.verifiedEvents).toBe(3);
    expect(result.brokenAtIndex).toBeUndefined();
  });

  it("returns 'broken' at the tampered event when payload is altered", async => {
    const tampered: CustodyEvent = {
      ...event2,
      data: { page: 999 },
      // hash field is unchanged -> tamper detection should fire
    };
    const result = await verifyChain([event1, tampered, event3]);
    expect(result.status).toBe("broken");
    expect(result.brokenAtIndex).toBe(1);
    expect(result.brokenAtEventHash).toBe(event2.hash);
    expect(result.verifiedEvents).toBe(1);
  });

  it("returns 'broken' when prev_hash linkage is wrong", async => {
    const detached: CustodyEvent = {
      ...event2,
      prev_hash: "0000000000000000000000000000000000000000000000000000000000000000",
    };
    const result = await verifyChain([event1, detached, event3]);
    expect(result.status).toBe("broken");
    expect(result.brokenAtIndex).toBe(1);
    expect(result.reason).toMatch(/Broken prev_hash/);
  });

  it("identifies tamper at index 0 when the very first event is altered", async => {
    const tampered: CustodyEvent = {
      ...event1,
      timestamp: "2099-12-31T23:59:59.999+00:00",
    };
    const result = await verifyChain([tampered, event2, event3]);
    expect(result.status).toBe("broken");
    expect(result.brokenAtIndex).toBe(0);
    expect(result.verifiedEvents).toBe(0);
  });
});
