{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-coordinator
  labels:
    {{- include "ocr-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ocr-local.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: coordinator
  endpoints:
    - port: http
      path: /api/v1/prometheus/
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
      {{- if .Values.secrets.metricsApiKey }}
      authorization:
        type: Bearer
        credentials:
          name: {{ .Release.Name }}-secret
          key: METRICS_API_KEY
      {{- end }}
{{- end }}
