#!/usr/bin/env python3
"""Generate Docker Compose YAML for multi-GPU worker deployments.

This script generates a docker-compose override file that deploys one
Celery OCR worker container per GPU, each pinned to a specific device
via CUDA_VISIBLE_DEVICES and the Docker device_ids reservation.

Usage:
    python scripts/generate_multi_gpu_compose.py --gpus 4
    python scripts/generate_multi_gpu_compose.py --gpus 2 --output docker-compose.workers.yml
    python scripts/generate_multi_gpu_compose.py --gpus 8 --vram-mb 24576 --concurrency 6
    python scripts/generate_multi_gpu_compose.py --gpus 4 --queues ocr_gpu --max-tasks-per-child 100
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# VRAM-based concurrency heuristic
# ---------------------------------------------------------------------------

VRAM_PER_TASK_MB = 4096
MAX_CONCURRENCY = 24
DEFAULT_CONCURRENCY = 4


def recommended_concurrency(vram_mb: int) -> int:
    """Calculate recommended worker concurrency based on GPU VRAM.

    Heuristic: ~4GB VRAM per concurrent OCR task.
    - 8GB  -> 2 workers
    - 16GB -> 4 workers
    - 24GB -> 6 workers
    - 48GB -> 12 workers

    Args:
        vram_mb: GPU VRAM in megabytes.

    Returns:
        Recommended concurrency (clamped to 1..24).
    """
    if vram_mb <= 0:
        return DEFAULT_CONCURRENCY  # safe default
    return max(1, min(vram_mb // VRAM_PER_TASK_MB, MAX_CONCURRENCY))


# ---------------------------------------------------------------------------
# YAML generation (no external deps -- pure string formatting)
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """\
# Auto-generated multi-GPU worker deployment
# Generated by: scripts/generate_multi_gpu_compose.py --gpus {gpu_count}
# Usage: docker compose -f docker-compose.coordinator.yml -f {output_filename} up -d
#
# Each worker is pinned to a single GPU via CUDA_VISIBLE_DEVICES and
# deploy.resources.reservations.devices.device_ids.
# Concurrency: {concurrency} task(s) per worker ({concurrency_source})
# Queues: {queues}
"""

_SERVICE_TEMPLATE = """\
  ocr-worker-gpu{idx}:
    build:
      context: ..
      dockerfile: coordinator/Dockerfile.worker
    environment:
      CELERY_BROKER_URL: ${{CELERY_BROKER_URL:?Set CELERY_BROKER_URL}}
      CELERY_RESULT_BACKEND: ${{CELERY_RESULT_BACKEND:?Set CELERY_RESULT_BACKEND}}
      DATABASE_URL: ${{DATABASE_URL:?Set DATABASE_URL}}
      DJANGO_SECRET_KEY: ${{DJANGO_SECRET_KEY:?Set DJANGO_SECRET_KEY}}
      DEPLOYMENT_ENV: ${{DEPLOYMENT_ENV:-development}}
      PRODUCTION_READINESS_ACK: ${{PRODUCTION_READINESS_ACK:-false}}
      NFS_ROOT: ${{NFS_ROOT:-/shared}}
      WORKER_QUEUES: ${{WORKER_QUEUES:-{queues}}}
      WORKER_CONCURRENCY: ${{WORKER_CONCURRENCY:-{concurrency}}}
      FASTTEXT_MODEL_PATH: ${{FASTTEXT_MODEL_PATH:-/app/models/lid.176.bin}}
      CUDA_VISIBLE_DEVICES: "{idx}"
{extra_env}
    command: >
      celery -A coordinator.coordinator worker
      -Q ${{WORKER_QUEUES:-{queues}}}
      -c ${{WORKER_CONCURRENCY:-{concurrency}}}
      --hostname worker-gpu{idx}@%h
      -l info
      --max-tasks-per-child {max_tasks}
    volumes:
      - ${{NFS_ROOT:-/shared}}:/shared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["{idx}"]
              capabilities: [gpu]
    restart: unless-stopped
"""


def generate_compose_yaml(
    gpu_count: int,
    concurrency: int,
    concurrency_source: str,
    queues: str,
    max_tasks_per_child: int,
    output_filename: str,
    per_gpu_queues: bool = False,
) -> str:
    """Generate a complete docker-compose YAML string.

    Args:
        gpu_count: Number of GPU workers to generate.
        concurrency: Celery concurrency per worker.
        concurrency_source: Human-readable description of how concurrency was chosen.
        queues: Comma-separated Celery queue names.
        max_tasks_per_child: Celery --max-tasks-per-child value.
        output_filename: Filename shown in the header usage comment.
        per_gpu_queues: When True, replace ``ocr_gpu`` with ``ocr_gpu_{idx}``
            per worker and inject ``ENABLE_PER_GPU_QUEUES`` / ``GPU_COUNT``
            environment variables.

    Returns:
        Complete YAML content as a string.
    """
    header = _HEADER_TEMPLATE.format(
        gpu_count=gpu_count,
        output_filename=output_filename,
        concurrency=concurrency,
        concurrency_source=concurrency_source,
        queues=queues,
    )

    services_block = "services:\n"
    for idx in range(gpu_count):
        if per_gpu_queues:
            gpu_queues = queues.replace("ocr_gpu", f"ocr_gpu_{idx}")
            extra_env = (
                f'      GPU_INDEX: "{idx}"\n'
                f'      ENABLE_PER_GPU_QUEUES: "true"\n'
                f'      GPU_COUNT: "{gpu_count}"'
            )
        else:
            gpu_queues = queues
            extra_env = f'      GPU_INDEX: "{idx}"'
        services_block += _SERVICE_TEMPLATE.format(
            idx=idx,
            concurrency=concurrency,
            queues=gpu_queues,
            max_tasks=max_tasks_per_child,
            extra_env=extra_env,
        )

    return header + "\n" + services_block


# ---------------------------------------------------------------------------
# Local GPU VRAM detection (best-effort, never fatal)
# ---------------------------------------------------------------------------

def _detect_gpu_vram_mb() -> int | None:
    """Attempt to detect GPU VRAM via nvidia-smi.

    Returns:
        VRAM in MB for GPU 0, or None if detection fails.
    """
    import subprocess

    try:
        result = subprocess.run(
            [
                "nvidia-smi",
                "--query-gpu=memory.total",
                "--format=csv,noheader,nounits",
                "--id=0",
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0 and result.stdout.strip():
            return int(result.stdout.strip().splitlines()[0])
    except (FileNotFoundError, subprocess.TimeoutExpired, ValueError, OSError):
        pass

    return None


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate Docker Compose YAML for multi-GPU OCR worker deployments. "
            "Produces one Celery worker service per GPU, each pinned to its device."
        ),
    )
    parser.add_argument(
        "--gpus",
        type=int,
        required=True,
        help="Number of GPUs to deploy workers for (>= 1).",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=None,
        help=(
            "Celery concurrency per worker. "
            "If omitted, auto-tuned from --vram-mb or local GPU detection."
        ),
    )
    parser.add_argument(
        "--vram-mb",
        type=int,
        default=None,
        help=(
            "GPU VRAM in megabytes for concurrency auto-tuning. "
            "Used when --concurrency is not set and local GPU detection fails."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output file path. Defaults to stdout.",
    )
    parser.add_argument(
        "--queues",
        type=str,
        default="ocr_gpu,cpu_general",
        help="Comma-separated Celery queue names (default: ocr_gpu,cpu_general).",
    )
    parser.add_argument(
        "--max-tasks-per-child",
        type=int,
        default=50,
        help="Celery --max-tasks-per-child value (default: 50).",
    )
    parser.add_argument(
        "--per-gpu-queues",
        action="store_true",
        help=(
            "Generate per-GPU queue names (ocr_gpu_0, ocr_gpu_1, ...) "
            "instead of the shared ocr_gpu queue."
        ),
    )
    return parser.parse_args(argv)


def run(args: argparse.Namespace) -> int:
    """Execute the generator with parsed arguments.

    Args:
        args: Parsed CLI arguments.

    Returns:
        0 on success, non-zero on error.
    """
    # Validate --gpus
    if args.gpus < 1:
        print("ERROR: --gpus must be >= 1", file=sys.stderr)
        return 1

    # Validate --max-tasks-per-child
    if args.max_tasks_per_child < 1:
        print("ERROR: --max-tasks-per-child must be >= 1", file=sys.stderr)
        return 1

    # Determine concurrency
    if args.concurrency is not None:
        if args.concurrency < 1:
            print("ERROR: --concurrency must be >= 1", file=sys.stderr)
            return 1
        concurrency = args.concurrency
        concurrency_source = "user-specified"
    elif args.vram_mb is not None:
        concurrency = recommended_concurrency(args.vram_mb)
        concurrency_source = f"auto-tuned from {args.vram_mb} MB VRAM"
    else:
        # Try local GPU detection
        detected_vram = _detect_gpu_vram_mb()
        if detected_vram is not None:
            concurrency = recommended_concurrency(detected_vram)
            concurrency_source = f"auto-tuned from detected {detected_vram} MB VRAM"
        else:
            concurrency = DEFAULT_CONCURRENCY
            concurrency_source = (
                f"default ({DEFAULT_CONCURRENCY}); "
                "use --vram-mb or --concurrency to override"
            )

    # Determine output filename for the header comment
    if args.output is not None:
        output_filename = args.output.name
    else:
        output_filename = f"docker-compose.multi-gpu-{args.gpus}.yml"

    # Generate YAML
    yaml_content = generate_compose_yaml(
        gpu_count=args.gpus,
        concurrency=concurrency,
        concurrency_source=concurrency_source,
        queues=args.queues,
        max_tasks_per_child=args.max_tasks_per_child,
        output_filename=output_filename,
        per_gpu_queues=args.per_gpu_queues,
    )

    # Write output
    if args.output is not None:
        try:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(yaml_content, encoding="utf-8")
            print(
                f"Generated {args.output} "
                f"({args.gpus} GPU workers, concurrency={concurrency})",
                file=sys.stderr,
            )
        except OSError as exc:
            print(f"ERROR: Failed to write {args.output}: {exc}", file=sys.stderr)
            return 1
    else:
        sys.stdout.write(yaml_content)

    return 0


def main(argv: list[str]) -> int:
    """Main entry point."""
    args = parse_args(argv)
    return run(args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
